require: 
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'bin/**/*'
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/HashSyntax:
  EnforcedShorthandSyntax: never