import "jquery2"
import "@hotwired/turbo-rails";
import "controllers";
import "jquery";
import "select2"
import "popper";
import "bootstrap";
import "dropzone";
import "chartkick"
import "Chart.bundle"
import "bootstrap-datepicker"
